
const actionTypes = {

  FETCH_ORG_REQUEST: 'FETCH_ORG_REQUEST',
  FETCH_ORG_COMPLETE: 'FETCH_ORG_COMPLETE',
  FETCH_ORG_FAIL: 'FETCH_ORG_FAIL',

  FETCH_DEPARTMENT_REQUEST: 'FETCH_DEPARTMENT_REQUEST',
  FETCH_DEPARTMENT_COMPLETE: 'FETCH_DEPARTMENT_COMPLETE',
  FETCH_DEPARTMENT_FAIL: 'FETCH_DEPARTMENT_FAIL',

  ADD_RECIPIENT_TO: 'ADD_RECIPIENT_TO',
  ADD_RECIPIENT_CC: 'ADD_RECIPIENT_CC',
  ADD_RECIPIENT_BCC: 'ADD_RECIPIENT_BCC',
  REMOVE_RECIPIENT: 'REMOVE_RECIPIENT'
}

Object.freeze(actionTypes);

export default actionTypes;
